# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a7bb14f3ac53741b7cd2f3ba21563f962dca73f51efde3bda33f08edc67ad1351c990189891127abe29970f73a3f7009aa9e94ea634513fb9641724f3fabce5

test:
  secret_key_base: e04a5d4f713d34dc401df59318f62135da5609c31f78532ab31433cb637d7c152ecd8ef31cc28d4b16117d76b4232f3995b256bd5f78fdce0ad4bbee4ffde7f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
